import { html, css, javascript, tailwind, react, github, sass, git, linkedIn, twitter, project1, project2, project3, project4, project5, project6, project7, project8, project9, project10, project11, project12, project13 } from '../assets'

export const technologies = [
  {
    id: 1,
    title: 'HTML5',
    icon: html,
  },
  {
    id: 2,
    title: 'CSS3',
    icon: css,
  },
  {
    id: 3,
    title: 'JAVASCRIPT',
    icon: javascript,
  },
  {
    id: 4,
    title: 'TAILWIND',
    icon: tailwind,
  },
  {
    id: 5,
    title: 'REACT',
    icon: react,
  },
  {
    id: 6,
    title: 'GITHUB',
    icon: github,
  },
  {
    id: 7,
    title: 'SASS',
    icon: sass,
  },
  {
    id: 8,
    title: 'GIT',
    icon: git,
  },
]

export const footerLinks = [
  {
    id: 1,
    link: 'https://www.linkedin.com/in/ayomide-dosunmu-252489182',
    icon: linkedIn,
    title: 'LinkedIn',
    message: 'Connect with me on linkedIn',
  },
  {
    id: 2,
    link: 'https://github.com/Doswin5',
    icon: github,
    title: 'Github',
    message: 'Connect with me on Github',
  },
  {
    id: 3,
    link: 'https://twitter.com/DosunmuAyomide',
    icon: twitter,
    title: 'Twitter',
    message: 'Connect with me on Twitter',
  },
]

export const projects = [
  {
    id: 1,
    rank: '01',
    // link: 'https://wosam-arena.vercel.app/',
    link: 'https://wosamarena.com/',
    image: project7,
    title: 'Wosam Arena Website',
    responsiveness: 'Large and Mobile screens (LIVE!)',
    description: 'Connect with me on linkedIn',
  },
  {
    id: 2,
    rank: '02',
    link: 'https://car-showroom-hub.vercel.app/',
    image: project13,
    title: 'Car Showroom Hub Website',
    responsiveness: 'Large and Mobile screens (Still in Progress)',
    description: 'Connect with me on linkedIn',
  },
  {
    id: 3,
    rank: '03',
    link: 'https://megastore-ecommerce.vercel.app/',
    image: project12,
    title: 'Megastore E-commerce Website',
    responsiveness: 'Large screen only (Still in Progress)',
    description: 'Connect with me on linkedIn',
  },
  {
    id: 4,
    rank: '04',
    link: 'https://mlc-home-rentals.vercel.app/',
    image: project11,
    title: 'MLC Home Rentals',
    responsiveness: 'Large screen only',
    description: 'Connect with me on linkedIn',
  },
  {
    id: 5,
    rank: '05',
    link: 'https://recutio-hr-platform.vercel.app/',
    image: project10,
    title: 'Recruito HR Website',
    responsiveness: 'Large and Mobile screens',
    description: 'Connect with me on linkedIn',
  },
  {
    id: 6,
    rank: '06',
    link: 'https://okra-doswin5.vercel.app/',
    image: project8,
    title: 'Okra Financial Website',
    responsiveness: 'Large and Mobile screens',
    description: 'Connect with me on linkedIn',
  },
  {
    id: 7,
    rank: '07',
    link: 'https://bank-modern-app-doswin5.vercel.app/',
    image: project2,
    title: 'Hoo Bank',
    responsiveness: 'Large and Mobile screens',
    description: 'Connect with me on linkedIn',
  },
  {
    id: 8,
    rank: '08',
    link: 'https://holmes-education.vercel.app/',
    image: project9,
    title: 'Holmes Education Website',
    responsiveness: 'Large and Mobile screens',
    description: 'Connect with me on linkedIn',
  },
  {
    id: 9,
    rank: '09',
    link: 'https://e-commerce-doswin5.vercel.app/',
    image: project6,
    title: 'E-Commerce Website',
    responsiveness: 'Large and Mobile screens',
    description: 'Connect with me on linkedIn',
  },
  {
    id: 10,
    rank: '10',
    link: 'https://youtube-clone-doswin5.vercel.app/',
    image: project3,
    title: 'Youtube Clone',
    responsiveness: 'Large screens only',
    description: 'Connect with me on linkedIn',
  },
  {
    id: 11,
    rank: '11',
    link: 'https://music-player-doswin5.vercel.app/',
    image: project4,
    title: 'Music Player',
    responsiveness: 'Large and Mobile screens',
    description: 'Connect with me on linkedIn',
  },
  {
    id: 12,
    rank: '12',
    link: 'https://recipe-app-doswin5.vercel.app/',
    image: project5,
    title: 'Recipe App',
    responsiveness: 'Large and Mobile screens',
    description: 'Connect with me on linkedIn',
  },
  {
    id: 13,
    rank: '13',
    link: 'https://doswin5.github.io/Portfolio-Website/',
    image: project1,
    title: 'A Portfolio Website',
    responsiveness: 'Large screens only',
    description: 'Connect with me on linkedIn',
  },
]